<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Prompt:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<style>
    :root {
        --bs-primary: #136791;
        --bs-primary-rgb: 19, 103, 145;
    }

    body {
        font-family: 'Prompt', sans-serif;
        --bs-body-font-family: 'Prompt', sans-serif; /* Set the default font to "Prompt" */
        /* Optionally adjust other Bootstrap body styles as needed */
        --bs-body-font-size: 1rem;         /* Default font size */
        --bs-body-font-weight: 300;        /* Default font weight */
        --bs-body-line-height: 1.5;        /* Default line height */
    }

    .btn-primary {
        --bs-btn-color: #fff;                         /* Text color */
        --bs-btn-bg: #136791;                         /* Base background color */
        --bs-btn-border-color: #136791;               /* Base border color */
    
        --bs-btn-hover-color: #fff;                   /* Text color on hover */
        --bs-btn-hover-bg: #115e83;                   /* Hover background (10% darker) */
        --bs-btn-hover-border-color: #115e83;         /* Hover border (10% darker) */
    
        --bs-btn-focus-shadow-rgb: 19, 103, 145;      /* RGB for focus shadow using primary color */
    
        --bs-btn-active-color: #fff;                  /* Text color on active */
        --bs-btn-active-bg: #0f5575;                  /* Active background (20% darker) */
        --bs-btn-active-border-color: #0f5575;        /* Active border (20% darker) */
        --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125); /* Active shadow */
    
        --bs-btn-disabled-color: #fff;                /* Text color on disabled */
        --bs-btn-disabled-bg: #136791;                /* Disabled background color (same as base) */
        --bs-btn-disabled-border-color: #136791;      /* Disabled border color (same as base) */
    }
    /*
    .bg-light {
        --bs-light-rgb: 244, 245, 246; 
        --bs-bg-opacity: 1;
        background-color: rgba(var(--bs-light-rgb), var(--bs-bg-opacity)) !important;
    }*/

</style>